### ISSUE TITLE
Gattool

### ISSUE THREAD

**Issue by mrobinson835** [JoeyZhu/Thermometer#1]
H Joey - I would email you but your email address sin't appearing for me.

I am doing a similar project right now with a cc2541 and and USB dongle.

For sensing the temperature, what gattool did you use? Is it BTool?

I have the program on the cc2541 keyfob and I am stuck at how to read temperature values from it.

Thanks,

Mike

**Comment by JoeyZhu** [comment]
gattool is in bluez.
since you use cc2541 keyfob, you may use TI official tools to read temperature.
